#Turquaz Configuration
#Thu Apr 14 14:19:33 EEST 2005
invoice_template=template1.jrxml
serverPort=8877
dbType=Turquaz HSQLDB
username=admin
logoURL=
serverAddress=localhost
automatic.dispatch.note=true
dbName=turquaz
dbUsername=sa
password=YWRtaW4\=
remember_password=true
dbPassword=
