/*
 * Generated by XDoclet - Do not edit!
 */
package server.interfaces;

/**
 * Home interface for Service.
 */
public interface ServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Service";
   public static final String JNDI_NAME="ejb/Service";

   public server.interfaces.Service create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
