/*
 * Generated by XDoclet - Do not edit!
 */
package server.interfaces;

/**
 * Remote interface for Service.
 */
public interface Service
   extends javax.ejb.EJBObject
{
   /**
    * Business method
    */
   public com.turquaz.common.HttpServiceResponse callService( server.util.SessionInfo info,com.turquaz.common.HttpServiceRequest request )
      throws com.turquaz.engine.exceptions.TurquazException, java.rmi.RemoteException;

   /**
    * Business method
    */
   public java.lang.Object callService( java.lang.String serviceName,java.util.HashMap argMap )
      throws com.turquaz.engine.exceptions.TurquazException, java.rmi.RemoteException;

}
