hibernate.connection.provider_class=org.hibernate.connection.DatasourceConnectionProvider
hibernate.connection.datasource=java:/RMakroDS
hibernate.transaction.factory_class=org.hibernate.transaction.JTATransactionFactory
hibernate.transaction.manager_lookup_class=org.hibernate.transaction.JBossTransactionManagerLookup
hibernate.transaction.flush_before_completion=true
hibernate.transaction.auto_close_session=true
hibernate.query.factory_class=org.hibernate.hql.classic.ClassicQueryTranslatorFactory
hibernate.cache.use_query_cache=true
hibernate.cglib.use_reflection_optimizer=false